recipe: default.v1

assistant_id: 20230826-113411-burning-filament

language: "es"

pipeline:
- name: "SpacyNLP"
  model: "es_core_news_md"
- name: SpacyTokenizer
- name: SpacyFeaturizer
  pooling: mean
- name: CountVectorsFeaturizer
  analyzer: char_wb
  min_ngram: 1
  max_ngram: 5
- name: DIETClassifier
  epochs: 100
  constrain_similarities: true

policies:
  - name: MemoizationPolicy
  - name: RulePolicy
  - name: TEDPolicy
    max_history: 5
    epochs: 100

