recipe: default.v1

assistant_id: 20230826-113411-burning-filament

language: "es"

pipeline:
- name: "SpacyNLP"
  model: "es_core_news_md"
- name: SpacyTokenizer
- name: SpacyFeaturizer
  pooling: mean
- name: CountVectorsFeaturizer
  analyzer: char_wb
  min_ngram: 1
  max_ngram: 5
- name: DIETClassifier
  epochs: 100
  constrain_similarities: true
  intent_classification: { confidence_threshold: 0.7 }
  entity_recognition: { confidence_threshold: 0.7 }
- name: FallbackClassifier
  threshold: 0.7

policies:
  - name: MemoizationPolicy
  - name: RulePolicy
    core_fallback_threshold: 0.4
    core_fallback_action_name: "action_default_fallback"
    enable_fallback_prediction: True
  - name: TEDPolicy
    constrain_similarities: true
    max_history: 10
    epochs: 100

endpoints:
  action_endpoint:
    url: "http://localhost:5055/webhook"

